#!/bin/bash
if [ -z "$1" ]; then
    echo 'usage: post <title> [categories]'
    exit 0
fi

title=$1
name=`echo $title | sed 's/[^0-9a-zA-Z]/-/g' | tr A-Z a-z`
filename=`date +%Y-%m-%d`-${name}.markdown

shift 1
cat > "_posts/$filename"  << EOF
---
layout: post
title: "$title"
date: `date +%Y-%m-%d\ %H:%M:%S`
author: vjudge1
categories: $2
tags: $3
---

* content
{:toc}
EOF

echo 'New blog posted.'
